services:
  db:
    image: bitnami/postgresql:17
    ports:
      - '5472:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=automate
    volumes:
      - db-data:/bitnami/postgresql

volumes:
  db-data:
